### ISSUE TITLE
Error in executing test_replayable.ipynb

### ISSUE THREAD

**Issue by herambnemlekar** [baxter-flowers/promplib#3]
I was trying to run the code for promps on the Baxter robot at WPI. Can you help with this issue, please?

ImportError                               Traceback (most recent call last)
<ipython-input-5-406af8206a09> in <module>()
      4 import json
      5 from numpy.linalg import norm
----> 6 from promp.ros import ReplayableInteractiveProMP
      7 from baxter_commander import ArmCommander
      8 from baxter_commander.persistence import *

/home/heramb/ros_ws/src/promplib/src/promp/ros/__init__.py in <module>()
      1 from .bridge import ROSBridge
----> 2 from .interactive import InteractiveProMP
      3 from .ros import FK, IK
      4 from .qcartpromp import QCartProMP
      5 from .replayable import ReplayableInteractiveProMP

/home/heramb/ros_ws/src/promplib/src/promp/ros/interactive.py in <module>()
----> 1 from ..interactive import InteractiveProMP as _InteractiveProMP
      2 from .bridge import ROSBridge
      3 from numpy import mean
      4 
      5 

/home/heramb/ros_ws/src/promplib/src/promp/interactive.py in <module>()
      1 from numpy.linalg import norm
      2 from .ik import FK, IK
----> 3 from .qcartpromp import QCartProMP
      4 from os.path import join
      5 

/home/heramb/ros_ws/src/promplib/src/promp/qcartpromp.py in <module>()
      3 from os.path import join, exists
      4 from os import makedirs
----> 5 from .refiner import TrajectoryRefiner
      6 from .ik import FK
      7 import matplotlib.pyplot as plt

/home/heramb/ros_ws/src/promplib/src/promp/refiner.py in <module>()
----> 1 from bbolib.bbo.cost_function import CostFunction
      2 from bbolib.bbo.distribution_gaussian import DistributionGaussian
      3 from bbolib.bbo.updater import UpdaterCovarDecay
      4 from bbolib.bbo.run_optimization import runOptimization
      5 import numpy as np

ImportError: No module named bbolib.bbo.cost_function

**Comment by ymollard** [comment]
The missing dependency is [this package](https://github.com/baxter-flowers/dmpbbo).
To be installed with `python setup.py install` in the `python` folder.
I'll make it clearer in the README.
